version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/atlas
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/codedeploy/stop_server.sh
      timeout: 300
      runas: ec2-user
  # AfterInstall:
  #   - location: scripts/codedeploy/install_dependencies.sh
  #     timeout: 1800
  #     runas: ec2-user
  ApplicationStart:
    - location: scripts/codedeploy/start_server.sh
      timeout: 300
      runas: ec2-user
