name: Git EC2 Direct Deploy

on:
  # push:
  #   branches:
  #     - develop
  workflow_dispatch:


jobs:
  build-and-release:
    environment: development-direct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/build-ec2-atlas-agent.sh
          sparse-checkout-cone-mode: false

      - name: Setup ENV File
        run: |
          cat << 'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF
      
      - name: Copy EC2 build script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: scripts/build-ec2-atlas-agent.sh
          target: /home/${{ secrets.EC2_USERNAME }}/

      - name: Copy .env file to EC2 Instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: .env
          target: /home/${{ secrets.EC2_USERNAME }}/atlas/

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: source ~/.zshrc && zsh ~/scripts/build-ec2-atlas-agent.sh
